#!/bin/bash
# Assigns static ip address
# Koray Kalmaz (2013) - kalmaz@gmail.com

# Edit the following:

# path to /etc/network/interfaces file:
IPFILE="interfaces"

# DNS Servers:
IPNS="8.8.8.8 8.8.4.4"

WEBURL="https://github.com/vanwarantion/ip-assigner"
IPPREF="static"
IPCFG=`route -n | grep "^0.*UG"`
IPGW=`echo $IPCFG | awk '{print $2}'`
IPIFC=`echo $IPCFG | awk '{print $8}'`
IPADR=`ifconfig $IPIFC | \
    sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'`
IPMSK=`ifconfig $IPIFC | \
    sed -En 's/127.0.0.1//;s/.*inet.* (Mask:)?(([0-9]*\.){3}[0-9]*).*/\2/p'`

NMNAME="network-manager"
NMINSTALL=`dpkg -l | grep "^ii *$NMNAME " | wc -l`
if [ "$NMINSTALL" -gt "0" ]; then
    IPMODE="network-manager"
else
    IPMODE=`grep "iface $IPIFC" $IPFILE | awk '{print $4}'`
fi

echo -e "\nIP Configuration:"
echo -e "Interface: \t $IPIFC"
echo -e "IP address:\t $IPADR"
echo -e "Netmask:   \t $IPMSK"
echo -e "Gateway:   \t $IPGW"
echo -e "Config:    \t $IPMODE"
echo -e "\n"

changeip(){
    askval(){
        read -p "$1:" retval
        }
    # address
    echo "Changing IP configuration for $1"
    askval "1/5: Enter new IP address for $IPIFC [$IPADR]"
    IPADRN=${retval:-$IPADR}
    echo "Using $IPADRN"
    # netmask
    askval "2/5: Enter new netmask for $IPADRN [$IPMSK]"
    IPMSKN=${retval:-$IPMSK}
    echo "Using $IPMSKN"
    # network
    IFS="." read i1 i2 i3 i4 <<< "$IPADRN"
    IFS="." read m1 m2 m3 m4 <<< "$IPMSKN"
    IPNET="$((i1 & m1)).$(($i2 & m2)).$((i3 & m3)).$((i4 & m4))"
    askval "3/5: Enter new network for $IPADRN/$IPMSKN [$IPNET]"
    IPNETN=${retval:-$IPNET}
    # gateway
    askval "4/5: Enter new gateway for $IPNET [$IPGW]"
    IPGWN=${retval:-$IPGW}
    # dns-nameservers
    askval "5/5: Enter nameserver(s) for $IPIFC [$IPNS]"
    IPNSN=${retval:-$IPNS}
    # Generate patch
    SFLINE=`grep -n "iface eth0" $IPFILE| cut -d":" -f1`
    tmpdir=`mktemp -d`
    echo "$SFLINE""c$SFLINE,`expr $SFLINE + 8`" > $tmpdir/ipchange.patch
    echo -e "< `sed -n -e 10p $IPFILE`\n---" >> $tmpdir/ipchange.patch
    commented=`grep "iface eth0" $IPFILE`
    echo "> # $commented" >> $tmpdir/ipchange.patch
    echo "> # Autogenerated by ipchange:" >> $tmpdir/ipchange.patch
    echo "> # $WEBURL" >> $tmpdir/ipchange.patch
    echo "> iface $IPIFC inet static" >> $tmpdir/ipchange.patch
    echo ">         address         $IPADRN" >> $tmpdir/ipchange.patch
    echo ">         network         $IPNETN" >> $tmpdir/ipchange.patch
    echo ">         netmask         $IPMSKN" >> $tmpdir/ipchange.patch
    echo ">         gateway         $IPGWN" >> $tmpdir/ipchange.patch
    echo ">         dns-nameservers $IPNSN" >> $tmpdir/ipchange.patch
    # Create a copy for just in case..
    cp $IPFILE $IPFILE-original
    patch $IPFILE $tmpdir/ipchange.patch
    echo "$IPFILE has been patched using $tmpdir/ipchange.patch"
    echo "You may want to check this before restarting the network!"
    echo "This can be reversed by running the following command:"
    echo -e "\033[33m\npatch -R $IPFILE $tmpdir/ipchange.patch\033[0m"
    while true; do
        read -p "Restart network now? [Y/n]" yn
        case $yn in
            [Yy]* )
                echo "Stopping network..."
                /etc/init.d/networking stop
                echo "Starting network..."
                /etc/init.d/networking start
                break
                ;;
            [Nn]* )
                echo "Answered no. Skipping.."
                break
                ;;
            * )
                echo "Please answer Yes or No"
                ;;
        esac
    done
    }

changeip $IPIFC
